### ISSUE TITLE
UserBadge should use "user" instead of "client"

### ISSUE THREAD

**Issue by blackarcanis** [klapaudius/FOSOAuthServerBundle#22]
Hi @klapaudius !
In the class "Oauth2Authenticator" l99; this line:
`return new SelfValidatingPassport(new UserBadge($client->getUserIdentifier()), [$accessTokenBadge]);`

Should be replaced by this line (use the "user" variable):
`return new SelfValidatingPassport(new UserBadge($user->getUserIdentifier()), [$accessTokenBadge]);`

At least, on my side, the code can't work without doing this update. Or maybe it's a misconfiguration from the old FOSOAuthServerBundle I used previously?

Thank you!

**Comment by klapaudius** [comment]
Hi, regarding the [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749), the client is not the same as the end-user.
Client is in fact a third party app that can authenticate to get a granted access to protected ressources.

An AccessToken can have a standalone client with the grant type "client_credentials" which normally authenticates the third party app or a client and a end-user with grant type "password"

**Comment by SanderVerkuil** [comment]
Hi @klapaudius, it makes perfect sense, as the `User` that is using the endpoint is in fact the Client, and the Client is also a `UserInterface`.

In our use-case though, when accessing the `/api/me` endpoint, it returns information about the user who has signed in, or rather, information of the user who has granted the client to act on their behalf.

In version 2.0, when it still used the `AuthenticationProvider`, the User would indeed be the User who granted the client access.

In version 3.0 and onwards, the `Passport` that is returned returns the Identifier of the `Client`, which means that my `UserProvider` fails because it tries to find the `User` based on the Identifier of the `Passport`.

So in that sense, the behaviour of this bundle changed, even though the new behaviour would be the correct behaviour. How would you recommend that the Symfony application receives the User who has authorized the client?

I do see the `AccessTokenBadge`, so theoretically the system could fetch the user based on the AccessTokenBadge as well, but that's not how Symfony provides the User. Using the `getUser()` method in controllers would return the `Client`, and from the `Client`, we can't get back to the original `User` who authorised the client. So how would we get the User who granted the Client access on their behalf in an action?

**Comment by Michal-Szczepaniak** [comment]
I came here as I have troubles with 3.1 and authentication because exactly that, I'm getting client identifier which then fails to fetch user because it goes to provider which uses user username and that just fails

**Comment by jcrombez** [comment]
One possible solution is to create a custom UserProvider who returns a `Client` : 

```php
namespace App\Security;

use App\Entity\Client;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

class OAuthClientUserProvider implements UserProviderInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    public function refreshUser(UserInterface $user)
    {
    }

    public function supportsClass(string $class)
    {
    }

    public function loadUserByIdentifier(string $identifier): UserInterface
    {
        return $this->entityManager->getRepository(Client::class)->find($identifier);
    }
}
```

```yaml
security:
    # ...
    providers:
        # ...
        app_oauth_client_user_provider:
            id: App\Security\OAuthClientUserProvider

    firewalls:
        # ...
        oauth_user:
            pattern: ^/oauth/v2/user
            fos_oauth: true
            provider: app_oauth_client_user_provider
```

Then in your controller, the user is the acutal User and not the Client. I don't yet understand why it's the User and not the Client though, but at least it fixes the issue.

**Comment by valentine-morozov** [comment]
> One possible solution is to create a custom UserProvider who returns a `Client` :
> 
> ```
> namespace App\Security;
> 
> use App\Entity\Client;
> use Doctrine\ORM\EntityManagerInterface;
> use Symfony\Component\Security\Core\User\UserInterface;
> use Symfony\Component\Security\Core\User\UserProviderInterface;
> 
> class OAuthClientUserProvider implements UserProviderInterface
> {
>     public function __construct(
>         private readonly EntityManagerInterface $entityManager,
>     ) {
>     }
> 
>     public function refreshUser(UserInterface $user)
>     {
>     }
> 
>     public function supportsClass(string $class)
>     {
>     }
> 
>     public function loadUserByIdentifier(string $identifier): UserInterface
>     {
>         return $this->entityManager->getRepository(Client::class)->findOneByRandomId($identifier);
>     }
> }
> ```
> 
> ```yaml
> security:
>     # ...
>     providers:
>         # ...
>         app_oauth_client_user_provider:
>             id: App\Security\OAuthClientUserProvider
> 
>     firewalls:
>         # ...
>         oauth_user:
>             pattern: ^/oauth/v2/user
>             fos_oauth: true
>             provider: app_oauth_client_user_provider
> ```
> 
> Then in your controller, the current user is the acutal User and not the Client. I don't yet understand why it's the User and not the Client though, but at least it fixes the issue.

The solution doesn't work for me. I am using branch v3 with Symfony 5 and getting NULL as the user in the Controller
