### ISSUE TITLE
doctrine/dbal v4 - Type Array obsolete

### ISSUE THREAD

**Issue by drekinov** [klapaudius/FOSOAuthServerBundle#31]
`json` type replaced `array` and `object` types which internally used serialize to store data as text.
JSON is not drop-in replacement because it json_decode/encode data or use native JSON field types.

Considering all of that we need a conversion from array to json type to support dbal v4 for existing installations.

klapaudius/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml contains entity mappings

**Comment by klapaudius** [comment]
fixed in v5.0.5

**Comment by dirk-t** [comment]
Oh man. For this breaking change I wished it was not on patch level / micro release.
It will take some time that a noop like me to catch this thing.
It will definetly break runnig systems after update, because they will runnig in an exception.
ConversionException Could not convert database value a:0:{} to Doctrine Type json

**Comment by drekinov** [comment]
Yeah, that was part of the idea behind having it as issue and not direct PR because i was not sure how to handle it directly without breaking existing installations.
Moreover it seems that change from #28 is missing too

**Comment by klapaudius** [comment]
v5.0.6 has been released with old doctrine settings and with restored PRs
v5.1.0 has been released too with doctrine/dbal v4 compliancy
